# Generated by Django 4.1.7 on 2023-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ja',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ko',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub-title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_title_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub-title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_title_ja',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub-title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_title_ko',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub-title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ja',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ko',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ja',
            field=models.CharField(max_length=150, null=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ko',
            field=models.CharField(max_length=150, null=True, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, to='blogposts.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.ManyToManyField(help_text='What languages is this blogpost available in?', to='blogposts.language'),
        ),
    ]
